# Generated by Django 6.1 on 2026-08-16 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="manager.project"
            ),
        ),
    ]
