# Generated by Django 6.1 on 2026-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("URGENT", "URGENT"),
                    ("HIGH", "HIGH"),
                    ("MEDIUM", "MEDIUM"),
                    ("LOW", "LOW"),
                ],
                max_length=255,
            ),
        ),
    ]
