# Generated by Django 6.1 on 2026-08-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="is_manager",
        ),
    ]
