# Generated by Django 6.1 on 2026-08-19 19:20

from django.db import migrations


def create_manager_group(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")

    manager_group, created = group.objects.get_or_create(name="Manager")
    perms = permission.objects.filter(
        codename__in=[
            "add_task",
            "delete_task",
            "add_position",
            "change_position",
            "delete_position",
            "add_project",
            "change_project",
            "delete_project",
            "add_team",
            "change_team",
            "delete_team",
            "add_worker",
            "delete_worker",
            "add_tasktype",
            "change_tasktype",
            "delete_tasktype",
        ]
    )
    manager_group.permissions.set(perms)


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="is_manager",
        ),
        migrations.RunPython(create_manager_group),
    ]
