# Generated by Django 6.1 on 2026-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_remove_worker_is_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
