# Generated by Django 6.1 on 2026-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_alter_position_name_alter_project_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["priority"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "Urgent"), (1, "High"), (2, "Medium"), (3, "Low")]
            ),
        ),
    ]
