# Generated by Django 6.1 on 2026-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_alter_task_options_alter_task_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
